source 'https://rubygems.org'

gem 'rake'
gem 'puppet-lint'
gem 'rspec', '~> 2.14.1'
gem 'rspec-puppet'
gem 'rspec-system-puppet'
gem 'puppetlabs_spec_helper'
gem 'travis'
gem 'travis-lint'
gem 'puppet-syntax'
gem 'puppet', ENV['PUPPET_VERSION'] || '~> 3.2.0'
gem 'vagrant-wrapper'
gem 'puppet-blacksmith'
